version: '3'

services:
  share_session1:
    image: node:lts-alpine
    build: .
    container_name: share_session1
    working_dir: /app
    command: npm run serve
    ports:
      - 8080:8080
    volumes:
      - ./session1:/app